services:
  web:
    build: .
    container_name: tabula
    environment:
      APPLICATION_ENV: dev
      FLASK_DEBUG: 1
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    links:
      - postgres:postgres

  data:
    restart: always
    image: postgres:latest
    volumes:
      - .:/var/lib/postgresql
    command: "true"
    
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
version: "2"
