version: "2"
services:
  web:
    build: .
    container_name: tabula
    env_file:
      - '.env'
    ports:
      - "8080:8080"
      - "443:8080"
    depends_on:
      - postgres
    volumes:
      - .:/var/www
    links:
      - postgres:postgres

  data:
    restart: "no"
    image: postgres:9.6
    volumes:
      - .:/var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: postgresql/
    volumes_from:
      - data
    ports:
      - "5432:5432"