services:
  web:
    build: .
    container_name: tabula
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      APP_SETTINGS: "${APP_SETTINGS}"
      DATABASE_URL: "${DATABASE_URL}"
      SECRET_KEY: "${SECRET_KEY}"
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    links:
      - postgres:postgres

  data:
    restart: always
    image: postgres:latest
    volumes:
      - .:/var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: postgresql/
    volumes_from:
      - data
    ports:
      - "5432:5432"
version: "2"
