"""empty message

Revision ID: 2f91c2bb4ef1
Revises: 1184fd053dcd
Create Date: 2017-03-05 02:04:58.340022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f91c2bb4ef1'
down_revision = '1184fd053dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    op.add_column('concentration', sa.Column('group_code', sa.String(length=30), nullable=True))
    op.add_column('course', sa.Column('concentration_id', sa.Integer(), nullable=True))
    op.drop_constraint('course_department_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'concentration', ['concentration_id'], ['id'])
    op.drop_column('course', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_department_fkey', 'course', 'department', ['department'], ['id'])
    op.drop_column('course', 'concentration_id')
    op.drop_column('concentration', 'group_code')
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_long', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='department_pkey')
    )
    # ### end Alembic commands ###
