"""empty message

Revision ID: 792fe157111d
Revises: 45bfc6421311
Create Date: 2017-03-07 19:54:17.732386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792fe157111d'
down_revision = '45bfc6421311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestones')
    op.drop_table('milestone')
    op.drop_table('interests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('milestone',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('milestone_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='milestone_pkey'),
    sa.UniqueConstraint('name', name='milestone_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('milestones',
    sa.Column('milestone_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], name='milestones_milestone_id_fkey')
    )
    # ### end Alembic commands ###
