"""empty message

Revision ID: 880f88839a57
Revises: 04ff2e75f61e
Create Date: 2017-02-23 21:33:28.310142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880f88839a57'
down_revision = '04ff2e75f61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('tokens', sa.Text(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'tokens')
    op.drop_column('user', 'name')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
