"""added synonyms to concentrations

Revision ID: 9c3853d22805
Revises: f61eed2b2aef
Create Date: 2017-04-03 04:25:20.494746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3853d22805'
down_revision = 'f61eed2b2aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concentration', sa.Column('synonym', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concentration', 'synonym')
    # ### end Alembic commands ###
