"""empty message

Revision ID: a352c8a6571e
Revises: 70b185326f4b
Create Date: 2017-02-20 05:35:31.806152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a352c8a6571e'
down_revision = '70b185326f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concentration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('name_short', sa.String(length=20), nullable=True),
    sa.Column('name_long', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_hash', sa.String(length=255), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=3), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('learning', sa.Integer(), nullable=True),
    sa.Column('enjoyment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_hash')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_hash', sa.String(length=255), nullable=True),
    sa.Column('concentration_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('ethnicity', sa.String(length=20), nullable=True),
    sa.Column('years_coding', sa.Float(), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['concentration_id'], ['concentration.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('user_history')
    op.drop_table('user')
    op.drop_table('semester')
    op.drop_table('course')
    op.drop_table('concentration')
    # ### end Alembic commands ###
