"""Introduce distinction between concentrations and departments + add fields to courses

Revision ID: b5ceeb584738
Revises: 9c3853d22805
Create Date: 2017-04-20 19:16:43.178602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ceeb584738'
down_revision = '9c3853d22805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('catalog_number', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('concentration', 'group_code')
    op.drop_column('concentration', 'synonym')
    op.add_column('course', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('prerequisites', sa.Text(), nullable=True))
    op.drop_constraint('course_concentration_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'department', ['department_id'], ['id'])
    op.drop_column('course', 'concentration_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('concentration_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_concentration_id_fkey', 'course', 'concentration', ['concentration_id'], ['id'])
    op.drop_column('course', 'prerequisites')
    op.drop_column('course', 'department_id')
    op.add_column('concentration', sa.Column('synonym', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.add_column('concentration', sa.Column('group_code', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_table('department')
    # ### end Alembic commands ###
