"""db schema v 0.0

Revision ID: c9cf9d9973b7
Revises: 
Create Date: 2017-03-23 22:13:40.251630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cf9d9973b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concentration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('group_code', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=6), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tokens', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvard_id', sa.Integer(), nullable=True),
    sa.Column('name_short', sa.String(length=20), nullable=True),
    sa.Column('name_long', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('concentration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concentration_id'], ['concentration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_hash', sa.String(length=255), nullable=False),
    sa.Column('concentration_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('ethnicity', sa.String(length=20), nullable=True),
    sa.Column('years_coding', sa.Float(), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['concentration_id'], ['concentration.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_hash')
    )
    op.create_table('tags',
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], )
    )
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_hash', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=3), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('tags')
    op.drop_table('user_profile')
    op.drop_table('course')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('semester')
    op.drop_table('concentration')
    # ### end Alembic commands ###
