"""empty message

Revision ID: d5ed23850b0e
Revises: 792fe157111d
Create Date: 2017-03-08 21:35:29.233570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ed23850b0e'
down_revision = '792fe157111d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semester', sa.Column('term', sa.String(length=6), nullable=True))
    op.add_column('semester', sa.Column('year', sa.String(length=4), nullable=True))
    op.drop_column('semester', 'name')
    op.drop_column('tag', 'description')
    op.drop_constraint('user_history_user_hash_key', 'user_history', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_history_user_hash_key', 'user_history', ['user_hash'])
    op.add_column('tag', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('semester', sa.Column('name', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('semester', 'year')
    op.drop_column('semester', 'term')
    # ### end Alembic commands ###
