"""added course_tags

Revision ID: f61eed2b2aef
Revises: c9cf9d9973b7
Create Date: 2017-03-23 22:14:41.616530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61eed2b2aef'
down_revision = 'c9cf9d9973b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_tags',
    sa.Column('user_history_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_history_id'], ['user_history.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_tags')
    # ### end Alembic commands ###
